# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: NuBits
email: matt@skycatchfire.com
description: "The World's First Stable Digital Currency"
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://hardcore-dev.github.io" # the base hostname & protocol for your site

# Build settings
markdown: kramdown

include: ["_pages"]

menu-list: ["About", "Exchanges", "Liquidity Pools", "Resources", "Connect", "NuShares", "Download"]
